### ISSUE TITLE
Doesn't seem to know it's in a git repo

### ISSUE THREAD

**Issue by boblindman** [dmytrobaida/GPTCommitVSCode#5]
Windows 10, VS code 1.77.1

I keep getting this error when generating a commit message "The current directory must be a Git repository!"

I have confirmed it's a Git repo and I can make commits if I manually enter a comment.  I have also established my Open IA key works,

**Comment by ParkingLotGames** [comment]
bumping, same error.
Made a simple lolcode folder to test after trying on an existing project, no dice.

![Screenshot_8](https://github.com/dmytrobaida/GPTCommitVSCode/assets/76890242/c51c78d6-772d-445e-a42a-5da1c3151a6c)

**Comment by Oxicode** [comment]
same error here!

**Comment by flavienbwk** [comment]
There is an alternative I use : https://github.com/lennartle/chadcommit

**Comment by Dowser** [comment]
Same error here  on my Windows machine, when I'm using the same extension synced over to my mac working with the same repo it works great.

**Comment by dmytrobaida** [comment]
Seems like this issue on all windows machines. Fixing it in new version

**Comment by dmytrobaida** [comment]
Should be fixed in version 1.0.5. Please create new issue if problem exists. Thanks
